### ISSUE TITLE
Dictionaries are only supported with string keys

### ISSUE THREAD

**Issue by sven-n** [MapsterMapper/Mapster#151]
First of all, thanks for this great project! It saves me a lot of time and works better than AutoMapper in my use case.

I just have a small problem: Why does the [DictionaryAdapter](https://github.com/MapsterMapper/Mapster/blob/845efa42913b68e25e5c23b97823f34802890a36/src/Mapster/Adapters/DictionaryAdapter.cs#L18) only support dictionaries with string keys? Any reason why integers or longs are not supported?

I saw a place where this is [hard coded](https://github.com/MapsterMapper/Mapster/blob/845efa42913b68e25e5c23b97823f34802890a36/src/Mapster/TypeAdapterConfig.cs#L67) a second time, too.

If I ignore all of that and try to use a IDictionary<int,> anyway, I'll run into an exception:

```
Mapster.CompileException : Error while compiling
source=ParentImplementationA
destination=ParentImplementationB
type=Map
  ----> Mapster.CompileException : Error while compiling
source=System.Collections.Generic.IDictionary`2[System.Int32,BaseChild]
destination=System.Collections.Generic.IDictionary`2[System.Int32,BaseChild]
type=Map
  ----> System.ArgumentException : Incorrect number of arguments supplied for call to method 'BaseChild get_Item(Int32)'
Parameter name: property
   at Mapster.TypeAdapterConfig.CreateMapExpression(CompileArgument arg, Boolean allowNull)
   at Mapster.TypeAdapterConfig.CreateMapExpression(TypeTuple tuple, MapType mapType)
   at Mapster.TypeAdapterConfig.CreateDynamicMapExpression(TypeTuple tuple)
   at Mapster.TypeAdapterConfig.<GetDynamicMapFunction>b__63_0[TDestination](TypeTuple tuple)
   at Mapster.TypeAdapterConfig.AddToHash(Hashtable hash, TypeTuple key, Func`2 func)
   at Mapster.TypeAdapterConfig.GetDynamicMapFunction[TDestination](Type sourceType)
   at Mapster.TypeAdapter.Adapt[TDestination](Object source, TypeAdapterConfig config)
   at ...
```

I wrote a short test case for that:
```csharp
        [Test]
        public void MapsterTest()
        {
            Mapster.TypeAdapterConfig<BaseParent, ParentImplementationB>.NewConfig();
            Mapster.TypeAdapterConfig<ParentImplementationA, ParentImplementationB>.NewConfig();

            Mapster.TypeAdapterConfig<BaseChild, ChildImplementationB>.NewConfig()
                .ConstructUsing(src => new ChildImplementationB());
            Mapster.TypeAdapterConfig<ChildImplementationA, ChildImplementationB>.NewConfig()
                .ConstructUsing(src => new ChildImplementationB());
            Mapster.TypeAdapterConfig.GlobalSettings.ForDestinationType<BaseChild>()
                .ConstructUsing(() => new ChildImplementationB());

            Mapster.TypeAdapterConfig.GlobalSettings.ForDestinationType<IDictionary<int, BaseChild>>()
                .ConstructUsing(() => new Dictionary<int, BaseChild>()); // shouldn't be required when it's handled by the DictionaryAdapter.

            var testParent = new ParentImplementationA();
            testParent.Name = "foo";
            testParent.Children.Add(new ChildImplementationA { ChildName = "bar" } );
            testParent.SomeDictionary.Add(2, new ChildImplementationA { ChildName = "in dictionary"});

            var adapted = testParent.Adapt<ParentImplementationB>();
            Assert.That(adapted, Is.TypeOf<ParentImplementationB>());
            Assert.That(adapted.Children, Has.Count.EqualTo(1));
            Assert.That(adapted.Children.First(), Is.TypeOf<ChildImplementationB>());
            Assert.That(adapted.SomeDictionary, Contains.Key(2));
            Assert.That(adapted.SomeDictionary[2], Is.TypeOf<ChildImplementationB>());
        }
    

    public class BaseParent
    {
        public string Name { get; set; }

        public ICollection<BaseChild> Children { get; set; } = new System.Collections.Generic.List<BaseChild>();

        public IDictionary<int, BaseChild> SomeDictionary { get; set; } = new Dictionary<int, BaseChild>();
    }

    public class BaseChild
    {
        public string ChildName { get; set; }
    }

    public class ParentImplementationA : BaseParent { }

    public class ParentImplementationB : BaseParent { }

    public class ChildImplementationA : BaseChild { }

    public class ChildImplementationB : BaseChild { }
```

If there's no real reason for that, I'd like to create to pull request to fix it :)

**Comment by sven-n** [comment]
Ah, I understand... but unfortunately I can’t expose Dictionary<int,...> in my real object model. I use adapter classes which implement IDictionary but are no regular Dictionaries.

However, I got it working locally with some little tweaks in the DictionaryAdapter. Unit tests all passed, but I’ll need to check some things when I’m back at my computer.
