### ISSUE TITLE
System.ArgumentException: Type 'AspNetCorePage.PagedList`1[ZLHP.Site.Contract.Dtos.SitesDto]' does not have a default constructor Parameter 

### ISSUE THREAD

**Issue by qgxcry** [MapsterMapper/Mapster#176]
try
            {
                var sites = await _sitesRepository.Value.FindAllPageListAsync(null, o => o.SiteID);
                var result = (sites).MapTo<PagedList<SitesDto>>();
                return result;
            }
            catch (Exception e)
            {
                throw e;
            }

{Mapster.CompileException: Error while compiling
        source=AspNetCorePage.PagedList`1[ZLHP.Site.Models.Sites]
        destination=AspNetCorePage.PagedList`1[ZLHP.Site.Contract.Dtos.SitesDto]
        type=Map ---> System.ArgumentException: Type 'AspNetCorePage.PagedList`1[ZLHP.Site.Contract.Dtos.SitesDto]' does not have a default constructor
        Parameter name: type
           at System.Linq.Expressions.Expression.New(Type type)
           at Mapster.Adapters.CollectionAdapter.CreateInstantiationExpression(Expression source, Expression destination, CompileArgument arg)
           at Mapster.Adapters.BaseAdapter.CreateBlockExpressionBody(Expression source, Expression destination, CompileArgument arg)
           at Mapster.Adapters.BaseAdapter.CreateExpressionBody(Expression source, Expression destination, CompileArgument arg)
           at Mapster.Adapters.BaseAdapter.CreateAdaptFunc(CompileArgument arg)
           at Mapster.TypeAdapterConfig.CreateMapExpression(CompileArgument arg, Boolean allowNull)
   --- End of inner exception stack trace ---
   at Mapster.TypeAdapterConfig.CreateMapExpression(CompileArgument arg, Boolean allowNull)
   at Mapster.TypeAdapterConfig.CreateMapExpression(TypeTuple tuple, MapType mapType)
   at Mapster.TypeAdapterConfig.CreateDynamicMapExpression(TypeTuple tuple)
   at Mapster.TypeAdapterConfig.<GetDynamicMapFunction>b__63_0[TDestination](TypeTuple tuple)
   at Mapster.TypeAdapterConfig.AddToHash(Hashtable hash, TypeTuple key, Func`2 func)
   at Mapster.TypeAdapterConfig.GetDynamicMapFunction[TDestination](Type sourceType)
   at Mapster.TypeAdapter.Adapt[TDestination](Object source, TypeAdapterConfig config)
   at ZLHP.Extensions.MapperExtensions.MapTo[T](Object obj) in D:\ZLSoft\Project\ZLHP\Source\ZLHP\ZLHP\Extensions\MapperExtensions.cs:line 14
   at ZLHP.Site.Services.Services.SiteService.GetSites() in D:\ZLSoft\Project\ZLHP\Source\ZLHP\ZLHP.Site\Services\SiteService.cs:line 28}

**Comment by chaowlert** [comment]
As exception said, PageList doesn't have default constructor, therefore Mapster cannot create object.

**Comment by qgxcry** [comment]
> As exception said, PageList doesn't have default constructor, therefore Mapster cannot create object.

{Mapster.CompileException: Error while compiling
source=ZLHP.Site.Models.Sites
destination=ZLHP.Site.Contract.Dtos.SitesDto
type=Map ---> System.InvalidOperationException: Cannot convert immutable type, please consider using 'MapWith' method to create mapping
   at Mapster.Adapters.PrimitiveAdapter.ConvertType(Expression source, Type destinationType, CompileArgument arg)
   at Mapster.Adapters.PrimitiveAdapter.CreateExpressionBody(Expression source, Expression destination, CompileArgument arg)
   at Mapster.Adapters.BaseAdapter.CreateAdaptFunc(CompileArgument arg)
   at Mapster.TypeAdapterConfig.CreateMapExpression(CompileArgument arg, Boolean allowNull)
   --- End of inner exception stack trace ---
   at Mapster.TypeAdapterConfig.CreateMapExpression(CompileArgument arg, Boolean allowNull)
   at Mapster.TypeAdapterConfig.CreateInlineMapExpression(Type sourceType, Type destinationType, MapType parentMapType, CompileContext context)
   at Mapster.Adapters.BaseAdapter.CreateAdaptExpression(Expression source, Type destinationType, CompileArgument arg)
   at Mapster.Adapters.CollectionAdapter.CreateListSet(Expression source, Expression destination, CompileArgument arg)
   at Mapster.Adapters.CollectionAdapter.CreateBlockExpression(Expression source, Expression destination, CompileArgument arg)
   at Mapster.Adapters.BaseAdapter.CreateBlockExpressionBody(Expression source, Expression destination, CompileArgument arg)
   at Mapster.Adapters.BaseAdapter.CreateExpressionBody(Expression source, Expression destination, CompileArgument arg)
   at Mapster.Adapters.BaseAdapter.CreateAdaptFunc(CompileArgument arg)
   at Mapster.TypeAdapterConfig.CreateMapExpression(CompileArgument arg, Boolean allowNull)}

**Comment by chaowlert** [comment]
Seemed like Mapster also cannot know how to create SitesDto object. Pls check wiki to learn more how to use. 

https://github.com/MapsterMapper/Mapster/wiki/Data-types

**Comment by qgxcry** [comment]
> Seemed like Mapster also cannot know how to create SitesDto object. Pls check wiki to learn more how to use.
> 
> https://github.com/MapsterMapper/Mapster/wiki/Data-types

The PagedList class is an inherited IList interface. How can I convert PageList<Site> to PageList<SiteDto>?

**Comment by chaowlert** [comment]
Sorry Mapster support casting to `IList<>`, but it cannot casting to `Pagelist<>`.
