### ISSUE TITLE
Mapping to inherited interface not working

### ISSUE THREAD

**Issue by mattbrailsford** [MapsterMapper/Mapster#188]
I have the following mapping config defined
 
    config.NewConfig<OrderStatusSaveDto, IOrderStatus>()
        .ConstructUsing(src => null);

(**NB** ConstructUsing(src => null) is because I don't want the mapper to be in control of constructing the interface, it will always be passed an instance)

And then in a controller I receive an `OrderStatusSaveDto` from the post body (which is populated). I then retrieve an `IOrderStatus` entity from a service and call the following to map the properties over

    orderStatus.Adapt(entity);

After this call however, the entity hasn't been populated at all.

Should Mapster be able to map to an interface like this?

**Comment by mattbrailsford** [comment]
Ok, after a little more digging, I believe it's because my `IOrderStatus` interface is made up of a number of inherited interfaces and so the mapping is only mapping the interface owned properties. I would have thought in this scenario, but like inheritance on an entity, the mapper would map all properties, owned or inherited.

**Comment by chaowlert** [comment]
This is might actually a bug. Mapster use `type.GetProperties(...)` to retrieve all properties. This method for class, it will also return inherited properties. However for interface, it will only return declare properties.

Fixing this issue might has side effect, I will see how to fix this.

**Comment by IsmailHassani** [comment]
Dear @chaowlert i tried the latest version of this library but i don't get it to work. After running the compile command on startup to test for errors it throws an exception that the property is not found.

**Comment by chaowlert** [comment]
Per this unit test, it should work https://github.com/MapsterMapper/Mapster/blob/master/src/Mapster.Tests/WhenMappingToInterface.cs#L39

Otherwise, pls provide issue code.

**Comment by IsmailHassani** [comment]
Hi @chaowlert, 
My apologies for my late response. It has to do with the multiple projects i'm working on currently.
Today i took your unittest to check if this worked. I had to add an inherited interface without extra properties and tried to adapt it to an model. Same error occurs here.
It is not covered by the current tests because you do dto > interface.
I'm trying to map interface > dto.
`````
        [TestMethod]
        public void MapToInheritedInterfaceWithoutProperties()
        {
            var config = TypeAdapterConfig.GlobalSettings;
            TypeAdapterConfig<IInheritedDtoWithoutProperties, InheritedDto>.NewConfig()
                .Map(d => d.Id, s => s.Id)
                .Map(d => d.Name, s => s.Name)
                .IgnoreNonMapped(true);

            config.Compile();

            /// doesn't reach this point
            var dto = new InheritedDto
            {
                Id = 1,
                Name = "Test",
                DateOfBirth = new DateTime(1978, 12, 10),
                UnmappedSource = "Lorem ipsum"
            } as IInheritedDtoWithoutProperties;

            var idto = dto.Adapt<InheritedDto>(config);
        }

        public interface IInheritedDtoWithoutProperties : IDto
        {
        }
`````
Maybe that's why it does not work?
Btw it happens on compilation of the typeadapter.

The exception thrown is: 
`````
'Id' is not a member of type 'Mapster.Tests.WhenMappingToInterface+IInheritedDtoWithoutProperties'
Parameter name: propertyOrFieldName
`````

`````
   at System.Linq.Expressions.Expression.PropertyOrField(Expression expression, String propertyOrFieldName)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Mapster.Utils.ExpressionEx.PropertyOrFieldPath(Expression expr, String path) in C:\Projects\Mapster\src\Mapster\Utils\ExpressionEx.cs:line 23
   at Mapster.Models.InvokerModel.GetInvokingExpression(Expression exp, MapType mapType) in C:\Projects\Mapster\src\Mapster\Models\InvokerModel.cs:line 37
   at Mapster.ValueAccessingStrategy.CustomResolverFn(Expression source, IMemberModel destinationMember, CompileArgument arg) in C:\Projects\Mapster\src\Mapster\Settings\ValueAccessingStrategy.cs:line 42
   at Mapster.Adapters.BaseClassAdapter.<>c__DisplayClass4_1.<CreateClassConverter>b__2(Func`4 fn, Expression src) in C:\Projects\Mapster\src\Mapster\Adapters\BaseClassAdapter.cs:line 40
   at System.Linq.Enumerable.<SelectManyIterator>d__167`3.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Mapster.Adapters.BaseClassAdapter.CreateClassConverter(Expression source, ClassModel classModel, CompileArgument arg, Expression destination) in C:\Projects\Mapster\src\Mapster\Adapters\BaseClassAdapter.cs:line 38
   at Mapster.Adapters.ClassAdapter.CreateInlineExpression(Expression source, CompileArgument arg) in C:\Projects\Mapster\src\Mapster\Adapters\ClassAdapter.cs:line 169
   at Mapster.Adapters.BaseAdapter.CreateInlineExpressionBody(Expression source, CompileArgument arg) in C:\Projects\Mapster\src\Mapster\Adapters\BaseAdapter.cs:line 304
   at Mapster.Adapters.BaseAdapter.CreateExpressionBody(Expression source, Expression destination, CompileArgument arg) in C:\Projects\Mapster\src\Mapster\Adapters\BaseAdapter.cs:line 107
   at Mapster.Adapters.BaseAdapter.CreateAdaptFunc(CompileArgument arg) in C:\Projects\Mapster\src\Mapster\Adapters\BaseAdapter.cs:line 28
   at Mapster.TypeAdapterConfig.CreateMapExpression(CompileArgument arg) in C:\Projects\Mapster\src\Mapster\TypeAdapterConfig.cs:line 349
`````
