### ISSUE TITLE
Question: Is there really no way to debug mappings in .net core?

### ISSUE THREAD

**Issue by daniefer** [MapsterMapper/Mapster#204]
I am trying to debug a string to int conversion error ("Input string was not in a correct format") in a .net core app and after searching around all I was able to find was the [Debugging Wiki](https://github.com/chaowlert/Mapster/wiki/Debugging) and #76. The wiki says:
>Net Core support
Currently, step-into debugging is working only in .NET 4.x. .NET Core doesn't yet support.

and the solution linked in #76 asked for logging but the solution did not provide it. Is there really no way to get more info out when an exception occurs other than the almost useless stack trace below?
```
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(ReadOnlySpan`1 s, NumberStyles style, NumberFormatInfo info)
   at lambda_method(Closure , String )
   at Mapster.Utils.Enum`1.MatchByString(String val)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Mapster.Utils.Enum`1.Parse(String val)
   at lambda_method(Closure , ICollection`1 )
   at lambda_method(Closure , List`1 )
   at Program() in C:\Repos\Example\Program.cs:line 165
```
I am shocked that such a populate mapping library does not provide more diagnostic info. I really hope I am just missing some reference or article that explains how to track issues like this down. Any help would be appreciated.

**Comment by chaowlert** [comment]
Step into debugging is supported for a while https://github.com/MapsterMapper/Mapster/wiki/Debugging

**Comment by chaowlert** [comment]
From StackTrace, in fact, it cannot convert from String to Enum. Hope this help.
