### ISSUE TITLE
Mapping must be called using ServiceAdapter 

### ISSUE THREAD

**Issue by sonsy-soft** [MapsterMapper/Mapster#230]
I get the same error after calling the scan method in code.
here is my Code

           ```
            var Config = GetConfiguration();
            Services.AddSingleton(Config);
            Services.AddScoped<IMapper, ServiceMapper>();
            Config.Scan(assemblies);

```
more informatino i use autofac for DI in .net core 3.1

**Comment by chaowlert** [comment]
Can you post your exception and stacktrace?

**Comment by sonsy-soft** [comment]
System.InvalidOperationException: Mapping must be called using ServiceAdapter
   at Mapster.TypeAdapterExtensions.GetService[TService](MapContext context)
   at Application.UserComment.Query.CommentConfig.Register(TypeAdapterConfig config) in D:\Work_Space_Manager\BaranRahmat\Project\Application\UserComment\Query\UserCommentListQuery.cs:line 61
   at Mapster.TypeAdapterConfig.Apply(IEnumerable`1 registers)
   at Mapster.TypeAdapterConfig.Scan(Assembly[] assemblies)
   at Configuration.MapperConfiguration.ScanMapster(ContainerBuilder builder, TypeAdapterConfig Config, Assembly[] assemblies) in D:\Work_Space_Manager\BaranRahmat\Project\Configuration\Configuration\MapperConfiguration.cs:line 117
   at WebUI.Startup.ConfigureContainer(ContainerBuilder builder) in D:\Work_Space_Manager\BaranRahmat\Project\WebUI\Startup.cs:line 52
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureContainerBuilder.InvokeCore(Object instance, Object container)
   at Microsoft.AspNetCore.Hosting.ConfigureContainerBuilder.<>c__DisplayClass10_0.<Invoke>g__StartupConfigureContainer|0(Object containerBuilder)
   at Microsoft.AspNetCore.Hosting.ConfigureContainerBuilder.Invoke(Object instance, Object container)
   at Microsoft.AspNetCore.Hosting.ConfigureContainerBuilder.<>c__DisplayClass8_0.<Build>b__0(Object container)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.ConfigureContainer[TContainer](HostBuilderContext context, TContainer container)
   at Microsoft.Extensions.Hosting.Internal.ConfigureContainerAdapter`1.ConfigureContainer(HostBuilderContext hostContext, Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at WebUI.Program.Main(String[] args) in D:\Work_Space_Manager\BaranRahmat\Project\WebUI\Program.cs:line 27

**Comment by chaowlert** [comment]
Can you show `Application.UserComment.Query.CommentConfig.Register(TypeAdapterConfig config)`?

**Comment by sonsy-soft** [comment]
it contains my config Dto
```
 public class CommentConfig: IRegister
    {
        public void Register(TypeAdapterConfig config)
        {
            var item = MapContext.Current.GetService<IServive>();

            config
                .NewConfig<Comment, CommentDto>()
                .IgnoreNullValues(true)
                .AddDestinationTransform((string x) => x.Trim())
                .Map(dest => dest.Title,        src => src.User.Title)
                .Map(dest => dest.Name,         src => src.User.Name)
                .Map(dest => dest.Family,       src => src.User.Name)
                .Map(dest => dest.Avatar,       src => src.User.Avatar)
                .Map(dest => dest.Confirmed,    src => src.State==Enums.CommentState.Show)
                ;
        }
    }
```

**Comment by chaowlert** [comment]
it is because of this command, pls remove

var item = MapContext.Current.GetService<IServive>();

**Comment by sonsy-soft** [comment]
I Need Some Service in the config 
how can i do it?

**Comment by chaowlert** [comment]
Is the service be used for Map function? If yes pls move to lambda.

`config.Map(dest => dest.Name, src => MapContext.Current.GetService<IServive>().Format(src.User.Name))`

**Comment by sonsy-soft** [comment]
is it a bug , isn't it ?
we usually need service for complex statement 
it's not only in a expression tree 
is there any solution else ?
how can fix it 
or add this feature to mapster?

**Comment by chaowlert** [comment]
if you mapping is complex, just wrap your complex statement into a function

**Comment by sonsy-soft** [comment]
you can improve the library just by add an overload for Map Method that it get labmda expression in arguments. 
now Map Method accept expression tree only.
if you add this feature you help many developer that use mapster in complex story or solution
thank's alot

**Comment by Calabonga** [comment]
this approach is not working:
`config.Map(dest => dest.Name, src => MapContext.Current.GetService<IServive>().Format(src.User.Name))`

Exception appears:
`InvalidOperationException: Mapping must be called using ServiceAdapter`

**Comment by asymetrixs** [comment]
Is there any update on this? I am facing the same issue as @Calabonga 
`Exception thrown: 'System.InvalidOperationException' in Mapster.DependencyInjection.dll
An exception of type 'System.InvalidOperationException' occurred in Mapster.DependencyInjection.dll but was not handled in user code
Mapping must be called using ServiceAdapter`

**Comment by asymetrixs** [comment]
When using `item.Adapt<OtherClass>(mapper.Config)` I get the exception as mentioned above, however when using `mapper.Map<OtherClass>(item)` it works fine with `MapContext.Current.GetService<SomeService>()` in the mapping configuration.
