### ISSUE TITLE
Mapping to empty class

### ISSUE THREAD

**Issue by MisterOzzy** [MapsterMapper/Mapster#244]
Hello, I have exception when tried to map from source to destination and destination class doesn't have any properties and without configuration for this types.
Example 1:
Base class
`public class Base { }`
Derived class
`public class Derived : Base { }`

`var @base = new Base();
var der = @base.Adapt<Derived>();`           

Exception
`System.InvalidCastException : Unable to cast object of type 'Base' to type 'Derived'.
   at (Object )
   at Mapster.TypeAdapter.Adapt[TDestination](Object source, TypeAdapterConfig config)
   at Mapster.TypeAdapter.Adapt[TDestination](Object source)`

Example 2:
Class A
`public class A { }`
Class B
`public class B { }`

`var a = new A();
var b = a.Adapt<B>();`  

Exception
`Mapster.CompileException : Error while compiling
source=******.Tests+A
destination=******.Tests+B
type=Map
  ----> System.InvalidOperationException : Cannot convert immutable type, please consider using 'MapWith' method to create mapping
   at Mapster.TypeAdapterConfig.CreateMapExpression(CompileArgument arg)
   at Mapster.TypeAdapterConfig.CreateMapExpression(TypeTuple tuple, MapType mapType)
   at Mapster.TypeAdapterConfig.CreateDynamicMapExpression(TypeTuple tuple)
   at Mapster.TypeAdapterConfig.<GetDynamicMapFunction>b__67_0[TDestination](TypeTuple tuple)
   at Mapster.TypeAdapterConfig.AddToHash[T](Dictionary`2 hash, TypeTuple key, Func`2 func)
   at Mapster.TypeAdapterConfig.GetDynamicMapFunction[TDestination](Type sourceType)
   at Mapster.TypeAdapter.Adapt[TDestination](Object source, TypeAdapterConfig config)
   at Mapster.TypeAdapter.Adapt[TDestination](Object source)
   at ***********.Tests.Map() in **************
--InvalidOperationException
   at Mapster.Adapters.PrimitiveAdapter.ConvertType(Expression source, Type destinationType, CompileArgument arg)
   at Mapster.Adapters.PrimitiveAdapter.CreateExpressionBody(Expression source, Expression destination, CompileArgument arg)
   at Mapster.Adapters.BaseAdapter.CreateAdaptFunc(CompileArgument arg)
   at Mapster.TypeAdapterConfig.CreateMapExpression(CompileArgument arg)`

If it had config mapping like `config.ForType<Base, Derived>()` or derived class had at least one properties, there would be okay.

**Comment by chaowlert** [comment]
This is expect behavior. Mapster uses heuristic patterns to determine how to map object. Since the type has no property to map, it will map object by using Converter.Convert.

Could you describe your use case, why you would like to map empty type?

**Comment by MisterOzzy** [comment]
for e.g. I have "DoSomethingModel", I inherit "DoSomethingRequest : DoSomethingModel"  and "DoSomethingCommand : DoSomethingModel". Request needs for Controller and it contains some metadata for ASP .NET Core. Command needs for internal bussiness logic (CQS approach) using Mediator. So, I need to create request (it can be empty class) for every action in controller  then I do 'doSomethingRequest.Adapt<DoSomethingCommand>' and I have got an exception

**Comment by chaowlert** [comment]
I'm just realized that Mapster already support declare class mapping. It is defined in https://github.com/MapsterMapper/Mapster/wiki/Mapping-non-public-members#note-for-non-public-member-mapping.

Here is example https://dotnetfiddle.net/zmjtF5
