### ISSUE TITLE
Object reference not set to an instance of an object.    at lambda_method(Closure , Object )

### ISSUE THREAD

**Issue by geniuskld** [MapsterMapper/Mapster#274]
```
[Theory, AutoData]
        public void ConvertCounterpartyToBus(OperationLog operationLog, BankAccount bankAccount, Contract contract,
            Requisites requisites, PaymentInfo paymentInfo, Supervisor supervisor)
        {
            _fixture.Customizations.Add(new TypeRelay(typeof(TypeInfoBase), typeof(LegalEntityInfo)));
            var domainCounterparty = _fixture.Create<Counterparty>();
            domainCounterparty.BankAccounts.Add(bankAccount);
            domainCounterparty.SetAgreement(new Agreement());
            domainCounterparty.Contracts.Add(contract);
            domainCounterparty.Requisites = requisites;
            domainCounterparty.PaymentInfo = paymentInfo;
            domainCounterparty.Supervisor = supervisor;

            var busCounterparty = domainCounterparty.Adapt<Superbrands.Bus.Contracts.CSharp.MsPartners.Counterparty
                .Counterparty>();
}

```

**Exception:**
```
.ConvertCounterpartyToBus(operationLog: At 10/15/2020 14:05:10 by operatorIdff622648-2857-4030-aeff-b2c0ae3d4100 from source79b958a9-dcdb-448f-afcf-b3d50493fe96, bankAccount: BankAccount { AccountStatus = Unset, AccountType = Unset, BankName = "bankName0b0f999e-ed07-4b42-80e9-1344fda89749", BIK = "bik91f6d562-191b-4848-9800-2a9f09591c2c", CorrespondentAccount = "correspondentAccount7d43e8ba-b829-4153-b0d7-a30df3"..., ... }, contract: Contract { ContractGuid = null, CounterpartyRelationshipId = 153, DocumentId = 136, DomainEvents = [], EndTime = null, ... }, requisites: Requisites { INN = "innb25d71de-6617-47c2-a91c-2e6e31046edd", KPP = "kpp70da7a19-8654-4714-b358-f8518321fa98", OGRN = "ogrn33dcb1ab-4975-4b08-96b7-3fc4ab248a93", OKOPF = "okopfa22a574a-d39e-4896-ba89-e8459e4c68be", OKPO = "okpodc5f747d-ae36-4919-84f1-ed46aaa24535", ... }, paymentInfo: PaymentInfo { BIC = "BIC655720c7-1f3f-46a0-8d0f-0c696b50177a", CorrespondentAccount = "correspondentAccount7a1c8745-0974-4ec3-95fe-e5ccd5"..., NameBank = "nameBankf7d8e783-1533-49c6-9fd1-5d611b400c0b", PaymentAccount = "paymentAccountdad18c71-5b78-474f-a9e7-5aa9cbcb60e8" }, supervisor: Supervisor { Email = "Email1e0a0d33-54cb-4d61-a814-cac4eee5a321", Name = "Name41bb523b-991a-4115-a31a-688e71e4854a", Patronymic = "Patronymic5e4605a1-74e2-4c1f-85a7-3c9fff4808ab", Phone = "Phone780f0f37-4ef0-4da6-8af4-06527b242b5b", SurName = "SurName5f1aa952-2ab7-4a85-acee-63cdfaf3fc8e" })

System.NullReferenceException: Object reference not set to an instance of an object.

System.NullReferenceException
Object reference not set to an instance of an object.
   at lambda_method(Closure , Object )
   at Mapster.TypeAdapter.Adapt[TDestination](Object source, TypeAdapterConfig config)
   at Mapster.TypeAdapter.Adapt[TDestination](Object source)
   at Superbrands.Partners.Tests.BusMappingTests.ConvertCounterpartyToBus(OperationLog operationLog, BankAccount bankAccount, Contract contract, Requisites requisites, PaymentInfo paymentInfo, Supervisor supervisor)
```

**Comment by chaowlert** [comment]
Pls provide reproducible code. I cannot understand your post.

**Comment by geniuskld** [comment]
> Pls provide reproducible code. I cannot understand your post.

ok, i updated the description

**Comment by chaowlert** [comment]
Still not enough information to reproduce, can you provide all classes? And if you have mapping config, pls also provide.

**Comment by chaowlert** [comment]
Close as no information provided
