### ISSUE TITLE
Fluent api ForAllTypesInNamespace detect extra runtime types

### ISSUE THREAD

**Issue by daniaremon** [MapsterMapper/Mapster#307]
#### Issue description

After config everyting amd build, the fluent api recognize all types in the assembly. This provokes an error when WriteFile want to create a file with a name that includes not allowed characters like <

This is the error:
```console
Processing: Sample.FolderA.ValueObjectAge+<GetEqualityComponents>d__12
dotnet : Unhandled exception. System.IO.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son 
correctos. : 'C:\....\Dtos\<GetEqualityComponents>d__12Dto.g.cs'
At line:1 char:1
+ dotnet mapster model -a ....
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled excep...>d__12Dto.g.cs':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at Mapster.Tool.Program.WriteFile(String code, String path) in D:\git\Mapster\src\Mapster.Tool\Program.cs:line 32
   at Mapster.Tool.Program.CreateModel(ModelOptions opt, Type type, AdaptAttributeBuilder builder) in D:\git\Mapster\src\Mapster.Tool\Program.cs:line 207
   at Mapster.Tool.Program.GenerateModels(ModelOptions opt) in D:\git\Mapster\src\Mapster.Tool\Program.cs:line 134
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Mapster.Tool.Program.Main(String[] args) in D:\git\Mapster\src\Mapster.Tool\Program.cs:line 17
```
#### Steps to reproduce the issue

1. Install Mapster.Tool + create configClass
2. Create some Pocos with navigations properties (using types of other classes) in different namespaces.
3. Create fluent api config class, with  ForAllTypesInNamespace method includying those namespaces:

```c#
config.AdaptTo("[name]Dto")
            .ForAllTypesInNamespace(Assembly.GetExecutingAssembly(), typeof(Poco1).Namespace)
            .ForAllTypesInNamespace(Assembly.GetExecutingAssembly(), typeof(Poco2).Namespace)
            .ForAllTypesInNamespace(Assembly.GetExecutingAssembly(), typeof(Poco3).Namespace);
```

#### What's the expected result?

- normal generated Dtos files without the error.

#### What's the actual result?

- error indicates that other types appart from the Pocos are taking in account for generting Dtos.

#### Additional details / screenshot

Maybe a filter with Where, when assembly.GetTypes() is called can resolve this issue.
I solved using ForTypes and typeof(Poco1).Assembly.GetTypes().Where(...).ToArray()
But it would be nicer that logic is abstracted by ForAllTypesInNamespace.

Best Regards

**Comment by chaowlert** [comment]
There is ExcludeTypes function. Pls check if this help or not. If not pls help suggest method signature. PR is also welcome if you would like to contribute.

**Comment by daniaremon** [comment]
I checked and ExludeTypes not help, because at runtime, seems like exist extra types: 
```console
Processing: Sample.FolderA.ValueObjectAge+<GetEqualityComponents>d__12 
```
The class ValueObjectAge is my type.
But when mapster process the types, it process that strange type "ValueObjectAge+<GetEquality...>d_12".
If helps, my ValueObjectAge has a method called GetEqualityComponents method that is an implementation of an abstract method of a parent class.

Here is the parent class:
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects#value-object-implementation-in-c
