### ISSUE TITLE
Mapster.Tools error (0x80004003 (E_POINTER))

### ISSUE THREAD

**Issue by allejp** [MapsterMapper/Mapster#321]
Hi, i receive this error using this command: `dotnet mapster model -a "my.dll"`

my.dll is compiled with .NET 4.8 Framework.

Mapster version: 7.1.5
Maspter.Tools version: 8.0.1

```
Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Puntatore non valido. (0x80004003 (E_POINTER))
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Mapster.Tool.Extensions.Scan(CodeGenerationConfig config, Assembly assembly) in D:\git\Mapster\src\Mapster.Tool\Extensions.cs:line 177
   at Mapster.Tool.Program.GenerateModels(ModelOptions opt) in D:\git\Mapster\src\Mapster.Tool\Program.cs:line 123
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Mapster.Tool.Program.Main(String[] args) in D:\git\Mapster\src\Mapster.Tool\Program.cs:line 17
System.IO.FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Puntatore non valido. (0x80004003 (E_POINTER))
File name: 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```

**Comment by chaowlert** [comment]
Currently, Mapster.Tools supports only .NET Core 3 and .NET 5. And There is no plan to support .NET Framework. Feel free to fork and create PR.
