### ISSUE TITLE
ProjectToType with Mongodb Queryable

### ISSUE THREAD

**Issue by ziaulhasanhamim** [MapsterMapper/Mapster#366]
Is there any way to use the ProjectToType extension with IMongoQueryable of MongoDB c# driver? IMongoQueryable extends IQueryable.

**Comment by skalahonza** [comment]
I was solving a similar issue with AutoMaper. https://stackoverflow.com/a/66220779/4438653
You can cast the IQueryable back to IMongoQueryable.

**Comment by ziaulhasanhamim** [comment]
```c#
var posts = db.GetCollection<Post>("posts");

var postList = await ((IMongoQueryable<PostDto>)posts.AsQueryable()
    .ProjectToType<PostDto>())
    .ToListAsync();

class Post
{
    [BsonId]
    public ObjectId Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }
}

public record PostDto(string Title, string Description);
```
I tried that but got this exception
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'itemName')
   at MongoDB.Driver.Core.Misc.Ensure.IsNotNull[T](T value, String paramName)
   at MongoDB.Driver.Linq.Linq2Implementation.Expressions.SelectExpression..ctor(Expression source, String itemName, Expression selector)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.Pipeline.MethodCallBinders.SelectBinder.Bind(PipelineExpression pipeline, PipelineBindingContext bindingContext, MethodCallExpression node, IEnumerable`1 arguments)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.MethodInfoMethodCallBinder`1.Bind(PipelineExpression pipeline, TBindingContext bindingContext, MethodCallExpression node, IEnumerable`1 arguments)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.BindMethodCall(MethodCallExpression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.Bind(Expression node)
   at MongoDB.Driver.Linq.Linq2Implementation.Processors.Pipeline.PipelineBinder.Bind(Expression node, IBsonSerializerRegistry serializerRegistry)
   at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryProviderImpl`1.Prepare(Expression expression)
   at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryProviderImpl`1.Translate(Expression expression)
   at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryProviderImpl`1.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryableImpl`2.ToCursorAsync(CancellationToken cancellationToken)
   at MongoDB.Driver.IAsyncCursorSourceExtensions.ToListAsync[TDocument](IAsyncCursorSource`1 source, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\ziaul\\MapsterMongo\Program.cs:line 13       
   at Program.<Main>(String[] args)
```

**Comment by skalahonza** [comment]
This happened to me with automapper as well. What helped was writing the record in the old syntax with default constructor with no parameters.
```cs
public record PostDto 
{
   public string Title { get; init; }
   public string Description { get; init; }
}
```

**Comment by skalahonza** [comment]
If that doesn't work for you, the last resort workaround could be that you can fetch your MongoDb entities into list. Then call Adpat and perform the mapping in memory and not in database,

**Comment by ziaulhasanhamim** [comment]
> This happened to me with automapper as well. What helped was writing the record in the old syntax with default constructor with no parameters.
doesn't help

**Comment by skalahonza** [comment]
Well, according to this: https://github.com/MapsterMapper/Mapster/issues/403. This project might not be maintained anymore. So in my opinion you have two options:
1. Do mapping in memory
2. Switch to another mapping tool e.g. AutoMapper

**Comment by ziaulhasanhamim** [comment]
yeah you are correct. But I really like the way mapster does things. No need for di containers needed. Very simple mapping with extensions

**Comment by skalahonza** [comment]
Yes, it works very well with Entity Framework, however acts weird with MongoDb.

**Comment by ziaulhasanhamim** [comment]
it would be very sad if it's not maintained anymore

**Comment by andrerav** [comment]
Hi @ziaulhasanhamim, I'm currently working on streamlining the build and packaging and get a new version of Mapster.Tool as soon as possible. After that I can take a closer look at this issue. I've read through this thread but not sure if I am understanding the problem correctly. Can you give me a clear explanation of what kind of functionality is missing in Mapster to help you with this problem?

**Comment by ziaulhasanhamim** [comment]
@andrerav Anything on this?

**Comment by Ryba1986** [comment]
I'm using extension method:
`
public static IMongoQueryable<TResult> ProjectTo<TResult>(this IMongoQueryable query, TypeAdapterConfig config)
=>(IMongoQueryable<TResult>)query.ProjectToType<TResult>(config);
`

**Comment by ziaulhasanhamim** [comment]
@Ryba1986 does't that thow exception? For me it throws an exception

**Comment by Ryba1986** [comment]
I am using LinqProvider v3

**Comment by ziaulhasanhamim** [comment]
Thank you sir approximate your efforts. I was searching a solution for this for a lot of time.

**Comment by andrerav** [comment]
@ziaulhasanhamim Using ProjectToType() with IQueryable can cause problems in cases where there are asynchronous operations. I suggest that you materialize your query (with ToList(), for example) before doing any mapping. This should fix your problem.

**Comment by alex-tselikovsky** [comment]
I h

> ```cs
> var posts = db.GetCollection<Post>("posts");
> 
> var postList = await ((IMongoQueryable<PostDto>)posts.AsQueryable()
>     .ProjectToType<PostDto>())
>     .ToListAsync();
> 
> class Post
> {
>     [BsonId]
>     public ObjectId Id { get; set; }
> 
>     public string Title { get; set; }
> 
>     public string Description { get; set; }
> }
> 
> public record PostDto(string Title, string Description);
> ```
> 
> I tried that but got this exception
> 
> ```
> Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'itemName')
>    at MongoDB.Driver.Core.Misc.Ensure.IsNotNull[T](T value, String paramName)
>    at MongoDB.Driver.Linq.Linq2Implementation.Expressions.SelectExpression..ctor(Expression source, String itemName, Expression selector)
>    at MongoDB.Driver.Linq.Linq2Implementation.Processors.Pipeline.MethodCallBinders.SelectBinder.Bind(PipelineExpression pipeline, PipelineBindingContext bindingContext, MethodCallExpression node, IEnumerable`1 arguments)
>    at MongoDB.Driver.Linq.Linq2Implementation.Processors.MethodInfoMethodCallBinder`1.Bind(PipelineExpression pipeline, TBindingContext bindingContext, MethodCallExpression node, IEnumerable`1 arguments)
>    at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.BindMethodCall(MethodCallExpression node)
>    at MongoDB.Driver.Linq.Linq2Implementation.Processors.PipelineBinderBase`1.Bind(Expression node)
>    at MongoDB.Driver.Linq.Linq2Implementation.Processors.Pipeline.PipelineBinder.Bind(Expression node, IBsonSerializerRegistry serializerRegistry)
>    at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryProviderImpl`1.Prepare(Expression expression)
>    at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryProviderImpl`1.Translate(Expression expression)
>    at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryProviderImpl`1.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
>    at MongoDB.Driver.Linq.Linq2Implementation.MongoQueryableImpl`2.ToCursorAsync(CancellationToken cancellationToken)
>    at MongoDB.Driver.IAsyncCursorSourceExtensions.ToListAsync[TDocument](IAsyncCursorSource`1 source, CancellationToken cancellationToken)
>    at Program.<Main>$(String[] args) in C:\Users\ziaul\\MapsterMongo\Program.cs:line 13       
>    at Program.<Main>(String[] args)
> ```

I tried this code and it works correct if use MongoDb.Driver v2.19.0 and it gets exception in v2.18.0. I think it was bug of MongoDb.Driver

**Comment by Ryba1986** [comment]
> @Ryba1986 does't that thow exception? For me it throws an exception

> I am using LinqProvider v3

> I tried this code and it works correct if use MongoDb.Driver v2.19.0 and it gets exception in v2.18.0. I think it was bug of MongoDb.Driver

MongoDb.Driver before v2.19.0 using LinqProvider v2 for default.
