### ISSUE TITLE
Mapster.EFCore does not support .net 6

### ISSUE THREAD

**Issue by tcattel** [MapsterMapper/Mapster#394]
Mapster.EFCore.Tests 
- change from .netcore3.1 to .net 6
- update nugets
- run EFCoreTest.TestFindObject
-
             dto.BuildAdapter()
                .**EntityFromContext**(context)
                .AdaptTo(poco);

Test method Mapster.EFCore.Tests.EFCoreTest.TestFindObject threw exception: 
System.MissingMethodException: **Method not found**: 'System.Type Microsoft.EntityFrameworkCore.Metadata.ITypeBase.get_ClrType()'.
    at Mapster.TypeAdapterBuilderExtensions.<>c__DisplayClass0_0`1.<EntityFromContext>b__0(TypeAdapterConfig config)
   at Mapster.TypeAdapterConfig.<>c__DisplayClass99_0.<Fork>b__0(String _) in C:\Dev\Github\Mapster\src\Mapster\TypeAdapterConfig.cs:line 705
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Mapster.TypeAdapterConfig.Fork(Action`1 action, String key1, Int32 key2) in C:\Dev\Github\Mapster\src\Mapster\TypeAdapterConfig.cs:line 702
   at Mapster.TypeAdapterBuilder`1.ForkConfig(Action`1 action, String key1, Int32 key2) in C:\Dev\Github\Mapster\src\Mapster\TypeAdapterBuilder.cs:line 39
   at Mapster.TypeAdapterBuilderExtensions.EntityFromContext[TSource](TypeAdapterBuilder`1 builder, DbContext context) in C:\Dev\Github\Mapster\src\Mapster.EFCore\TypeAdapterBuilderExtensions.cs:line 18
   at Mapster.EFCore.Tests.EFCoreTest.TestFindObject() in C:\Dev\Github\Mapster\src\Mapster.EFCore.Tests\EFCoreTest.cs:line 37

**Comment by Philippe-Laval** [comment]
I have created a pull request with all projects compiled with net6.0.
In this case, all unit tests are passing including the one you described.

**Comment by Philippe-Laval** [comment]
In case, you want to test it : it is here 
https://github.com/Philippe-Laval/Mapster

**Comment by tcattel** [comment]
All the test pass
- except one interminently **Explicit_Mapping_Requirement_Throws_Before_Mapping_Attempted**
- 91 warnings that for some can easily be removed

**Comment by Philippe-Laval** [comment]
The warning are coming from change in project where code is now copiled with nullable warning, I guess. 
I did not take the time to remove the warning since the source code can be compiled for older targets (where nullable is not defined). I just wanted to use mapster.tool and start using mapster.
I guess people maintining the project have more knowledge than me.

**Comment by tcattel** [comment]
got it

**Comment by sang-sakarin** [comment]
@Philippe-Laval Can you explain how to install this package from your repository.  I wait for long time to accept merge request.

**Comment by Philippe-Laval** [comment]
@sang-sakarin Hello ! In fact I was expected to have the maintainer of the project update his code. I guess we should ask him if he can do it. 
For my repository, I didn't create a nuget (I expected we could use the official build), so you have to duplicate the repository, build it and then use the dll or the tool as shown in an two examples in my account.

**Comment by apphost** [comment]
still not fixed yet?

**Comment by QadiymStewart** [comment]
Doesn't work still getting an error 

[2022-08-08T14:42:57.453Z] Error: System.MissingMethodException: Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.ITypeBase.get_ClrType()'.
   at Mapster.TypeAdapterBuilderExtensions.<>c__DisplayClass0_0`1.<EntityFromContext>b__0(TypeAdapterConfig config)
   at Mapster.TypeAdapterConfig.<>c__DisplayClass99_0.<Fork>b__0(String _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Mapster.TypeAdapterConfig.Fork(Action`1 action, String key1, Int32 key2)
   at Mapster.TypeAdapterBuilderExtensions.EntityFromContext[TSource](TypeAdapterBuilder`1 builder, DbContext context)
