### ISSUE TITLE
Maping record types with properties and constructors

### ISSUE THREAD

**Issue by sajjadsaharkhan** [MapsterMapper/Mapster#490]
hi. thanks for this powerful and developer-friendly library
I want to map to `record` with this senario:

``` csharp
using System.Text.Json;
using Mapster;

var sourceInstance = new MyDTOWithConstructor(2, "Sajjad");

var targetInstance = sourceInstance.Adapt<MyDTOWithPropertyAndConstructor>();
targetInstance.ParentId = 1; 

Console.WriteLine(JsonSerializer.Serialize(targetInstance));

record MyDTOWithPropertyAndConstructor(int Id, string Name)
{
    public int ParentId { get; set; }
}

record MyDTOWithConstructor(int Id, string Name);
```

it throws this exception:
```
Unhandled exception. Mapster.CompileException: Error while compiling
source=MyDTOWithConstructor
destination=MyDTOWithPropertyAndConstructor
type=Map
 ---> System.InvalidOperationException: No default constructor for type 'MyDTOWithPropertyAndConstructor', please use 'ConstructUsing' or 'MapWith'
   at Mapster.Adapters.BaseAdapter.CreateInstantiationExpression(Expression source, Expression destination, CompileArgument arg)
   at Mapster.Adapters.ClassAdapter.CreateInstantiationExpression(Expression source, Expression destination, CompileArgument arg)
   at Mapster.Adapters.ClassAdapter.CreateInlineExpression(Expression source, CompileArgument arg)
   at Mapster.Adapters.BaseAdapter.CreateInlineExpressionBody(Expression source, CompileArgument arg)
   at Mapster.Adapters.BaseAdapter.CreateExpressionBody(Expression source, Expression destination, CompileArgument arg)
   at Mapster.Adapters.BaseAdapter.CreateAdaptFunc(CompileArgument arg)
   at Mapster.TypeAdapterConfig.CreateMapExpression(CompileArgument arg)
   --- End of inner exception stack trace ---
```
Is there a way to map with this scenario **without any additional code** such as MapWith or change Mapster GlobalConfig or custom config for this case?

**Comment by channeladam** [comment]
I just hit this error when trying to map a record type.  That's quite unfortunate.

**Comment by stagep** [comment]
In order to identify issues that are still active, we are closing issues that we believe are either resolved or are dormant. If your issue is still active then please reopen. Thanks.
