### ISSUE TITLE
Mapster.EFCore ProjectToType<T>().SingleOrDefault throwing exception

### ISSUE THREAD

**Issue by MortenRickiRasmussen** [MapsterMapper/Mapster#566]
Hi!

I have this piece of code 

``` c#
public async Task<T> SingleOrDefault(int id) 
{
  var query = DbContext.SomeEntity.Where(x => x.Id == id);

   return await _mapper.From(query).ProjectToType<T>().SingleOrDefaultAsync();
}
```

it throws the following Exception 

```
Data: System.MissingMethodException: Constructor on type 'Mapster.EFCore.MapsterAsyncEnumerable`1[[SomeSystem.SomeDto, SomeSystem.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Mapster.EFCore.MapsterQueryableProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken) .........
```

If i exchange the code to the following, it works fine

``` c#
public async Task<T> SingleOrDefault(int id) 
{
   var query = DbContext.SomeEntity.Where(x => x.Id == id);

   var list = await _mapper.From(query).ProjectToType<T>().ToListAsync();

   return list.FirstOrDefault();
}
```

Additional info:

AspNet 7.0
Mapster 7.3.0
Mapster.EFCore 5.1.0

**Comment by andrerav** [comment]
Have you tried materializing the list before calling ProjectToType()? There are some issues when using ProjectToType with async queries.

**Comment by andrerav** [comment]
Assuming this was solved by materializing the query first.

**Comment by SeiOkami** [comment]
Looks like a bug

![image](https://github.com/MapsterMapper/Mapster/assets/42138875/29c22f44-6a04-4ec4-b83a-9e24dc5761d3)
