### ISSUE TITLE
Issue creating config with Include when testing

### ISSUE THREAD

**Issue by JoMiGe** [MapsterMapper/Mapster#612]
We have developed a service using Mapster to map our model and more particularly the Include method to configure the mapping.
```csharp
    public TypeAdapterSetter<TSource, TDestination> Include<TDerivedSource, TDerivedDestination>()
      where TDerivedSource : class, TSource
      where TDerivedDestination : class, TDestination
    {
      return this.Include<TypeAdapterSetter<TSource, TDestination>>(typeof (TDerivedSource), typeof (TDerivedDestination));
    }
```

The issue happens when we run the tests (Integration tests). If the test is run unitary, it works. But when all the tests are run, we have the following exception on some tests.

  System.ArgumentOutOfRangeException
  capacity was less than the current size. (Parameter 'value')
     at System.Collections.Generic.List`1.set_Capacity(Int32 value)
     at System.Collections.Generic.List`1.Grow(Int32 capacity)
     at System.Collections.Generic.List`1.AddWithResize(T item)
     at Mapster.TypeAdapterSetterExtensions.Include[TSetter](TSetter setter, Type sourceType, Type destType)
     at Mapster.TypeAdapterSetter`2.Include[TDerivedSource,TDerivedDestination]()

The code is:
```csharp
        TypeAdapterConfig<ConfigurationModel, Configuration>
            .NewConfig()
            .Include<AValueModel, AValue>()
            .Include<BValueModel, BValue>()
            .Include<CValueModel,DValue>();
```

Any idea what could be the issue ?

Thank you ?

**Comment by benjaminoerskov** [comment]
Im getting the same error. Did you figure out how to fix it?

**Comment by Jofrais** [comment]
Got the same issue here...

**Comment by stagep** [comment]
In order to identify issues that are still active, we are closing issues that we believe are either resolved or are dormant. If your issue is still active then please reopen. Thanks.
