### ISSUE TITLE
Mapster.Tool throwing System.IO.FileNotFoundException when using version 8.4.1

### ISSUE THREAD

**Issue by stagep** [MapsterMapper/Mapster#635]
Since upgrading Mapster.Tool from 8.4.0-pre06 to 8.4.1, any mapping that references a type from a nuget package will throw an exception:
E.g. Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Google.Protobuf, Version=3.24.3.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'. The system cannot find the file specified.

I am using the latest version of Mapster (7.4.1-pre01). I have tested and got the exception in .Net 7 and .Net 8 projects.

I am using Google.Protobuf as an example of a nuget package and using the example type of ByteString

In the project file i have
`
<Target Name="Mapster" AfterTargets="AfterBuild">
		<Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster mapper -a &quot;$(TargetDir)$(ProjectName).dll&quot;" />
</Target>`

My mapping configuration is:

```using Google.Protobuf;
using Mapster;

namespace MapsterToolsException;

public class MapsterConfiguration : IRegister
{
    public void Register(TypeAdapterConfig config)
    {
        config.ForType<ByteString, byte[]>().MapWith(d => d.ToArray());
    }
}
```

You do not need to have any mappers defined to get the exception. 

There is a workaround. Manually copying the Google.Protobuf.dll to the build folder (e.g. bin/Debug/net7.0) will eliminate the exception.

**Comment by stagep** [comment]
Build output:

1>Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Google.Protobuf, Version=3.24.3.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'. The system cannot find the file specified.
1>File name: 'Google.Protobuf, Version=3.24.3.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'
1>   at MapsterToolsException.MapsterConfiguration.Register(TypeAdapterConfig config)
1>   at Mapster.TypeAdapterConfig.Apply(IEnumerable`1 registers) in C:\temp\Mapster-master\src\Mapster\TypeAdapterConfig.cs:line 752
1>   at Mapster.TypeAdapterConfig.Scan(Assembly[] assemblies) in C:\temp\Mapster-master\src\Mapster\TypeAdapterConfig.cs:line 731
1>   at Mapster.Tool.Program.GenerateMappers(MapperOptions opt) in C:\temp\Mapster-master\src\Mapster.Tool\Program.cs:line 66
1>   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
1>   at Mapster.Tool.Program.Main(String[] args) in C:\temp\Mapster-master\src\Mapster.Tool\Program.cs:line 19

**Comment by stagep** [comment]
More details of the exception:

1>Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Google.Protobuf, Version=3.24.3.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'. The system cannot find the file specified.
1>File name: 'Google.Protobuf, Version=3.24.3.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'
1>   at TimeKeeping.IO.UI.MapsterConfiguration.Register(TypeAdapterConfig config)
1>   at Mapster.TypeAdapterConfig.Apply(IEnumerable`1 registers) in C:\Projects\Mapster\src\Mapster\TypeAdapterConfig.cs:line 752
1>   at Mapster.TypeAdapterConfig.Scan(Assembly[] assemblies) in C:\Projects\Mapster\src\Mapster\TypeAdapterConfig.cs:line 731
1>   at Mapster.Tool.Program.GenerateMappers(MapperOptions opt) in C:\Projects\Mapster\src\Mapster.Tool\Program.cs:line 66
1>   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
1>   at Mapster.Tool.Program.Main(String[] args) in C:\Projects\Mapster\src\Mapster.Tool\Program.cs:line 19

**Comment by carumsoft** [comment]
I'm new to Mapster and i had similar problem.
You can not use AfterTargets="AfterBuild" path. This is not working.

I'm using on demand path with "dotnet build -p:CopyLocalLockFileAssemblies=true"
```
  <Target Name="Mapster">
	<Exec WorkingDirectory="$(ProjectDir)" Command="dotnet build -p:CopyLocalLockFileAssemblies=true" />
	<Exec WorkingDirectory="$(ProjectDir)" Command="dotnet tool restore" />
	<Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster model -a &quot;$(TargetDir)$(ProjectName).dll&quot;" />
	<Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster extension -a &quot;$(TargetDir)$(ProjectName).dll&quot;" />
	<Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster mapper -a &quot;$(TargetDir)$(ProjectName).dll&quot;" />
  </Target>
```

**Comment by stagep** [comment]
Thanks for the pointer. I was able to resolve by adding
`
<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
`
to my project file and it now works as this copies the libraries referenced from the nuget packages to the build folder and the Mapster.Tool process can now find the necessary files. I did not modify anything else.

For future reference, this was a client side library so by default, the nuget files are not copied to the build folder.

**Comment by andrerav** [comment]
I'm sorry for your troubles @stagep, and thanks for the help @carumsoft. I think that this should be added to the documentation in case other users are experiencing this. @stagep Is it possible for you to share more details on how your csproj is set up now?

**Comment by stagep** [comment]
The project is a class library referenced by MAUI and Blazor WASM projects. 

`
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" Version="3.24.3" />
        <PackageReference Include="Mapster" Version="7.4.1-pre01" />
    </ItemGroup>

    <Target Name="Mapster" AfterTargets="AfterBuild">
        <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet tool restore" />
        <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet mapster mapper -a &quot;$(TargetDir)$(ProjectName).dll&quot;" />
    </Target>
</Project>
`
Mapster.Tool 8.4.1-pre01 is installed.

**Comment by andrerav** [comment]
Awesome, thank you very much. I've added both of your workarounds to the wiki here: https://github.com/MapsterMapper/Mapster/wiki/Mapster.Tool#troubleshooting

**Comment by boylec** [comment]
I had this same issue with an assembly and the above solutions worked for me.

Then I added System.Text.Json for .NET 9 preview (which targets .NET 8)

```
<PackageReference Include="System.Text.Json" Version="9.0.0-preview.5.24306.7" />
```

Now the issue has returned.

```
System.IO.FileLoadException: Could not load file or assembly 'System.Text.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
  File name: 'System.Text.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   ---> System.IO.FileLoadException: Could not load file or assembly 'System.Text.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
     at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
     at System.Reflection.Assembly.LoadFrom(String assemblyFile)
     at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
     at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
     at System.ModuleHandle.ResolveMethod(QCallModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
     at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, ReadOnlySpan`1 typeInstantiationContext, ReadOnlySpan`1 methodInstantiationContext)
     at System.ModuleHandle.ResolveMethodHandle(Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
     at System.RuntimeType.GetMethodBase(RuntimeModule scope, Int32 typeMetadataToken)
     at System.Reflection.RuntimeCustomAttributeData..ctor(RuntimeModule scope, MetadataToken caCtorToken, ConstArray& blob)
     at System.Reflection.RuntimeCustomAttributeData.GetCustomAttributes(RuntimeModule module, Int32 tkTarget)
     at Mapster.Utils.NullableExpressionVisitor.VisitMember(MemberExpression node) in C:\Projects\Mapster\src\Mapster\Utils\NullableExpressionVisitor.cs:line 130
     at Mapster.Utils.NullableExpressionVisitor.Visit(Expression node) in C:\Projects\Mapster\src\Mapster\Utils\NullableExpressionVisitor.cs:line 50
     at Mapster.Utils.ExpressionEx.CanBeNull(Expression exp) in C:\Projects\Mapster\src\Mapster\Utils\ExpressionEx.cs:line 261
     at Mapster.Utils.ExpressionEx.ApplyNullPropagation(Expression getter) in C:\Projects\Mapster\src\Mapster\Utils\ExpressionEx.cs:line 317
     at Mapster.Adapters.BaseClassAdapter.CreateClassConverter(Expression source, ClassModel classModel, CompileArgument arg, Expression destination) in C:\Projects\Mapster\src\Mapster\Adapters\BaseClassAdapter.cs:line 59
     at Mapster.Adapters.ClassAdapter.CreateBlockExpression(Expression source, Expression destination, CompileArgument arg) in C:\Projects\Mapster\src\Mapster\Adapters\ClassAdapter.cs:line 100
     at Mapster.Adapters.BaseAdapter.CreateBlockExpressionBody(Expression source, Expression destination, CompileArgument arg) in C:\Projects\Mapster\src\Mapster\Adapters\BaseAdapter.cs:line 245
     at Mapster.Adapters.BaseAdapter.CreateExpressionBody(Expression source, Expression destination, CompileArgument arg) in C:\Projects\Mapster\src\Mapster\Adapters\BaseAdapter.cs:line 123
     at Mapster.Adapters.BaseAdapter.CreateAdaptFunc(CompileArgument arg) in C:\Projects\Mapster\src\Mapster\Adapters\BaseAdapter.cs:line 28
     at Mapster.TypeAdapterConfig.CreateMapExpression(CompileArgument arg) in C:\Projects\Mapster\src\Mapster\TypeAdapterConfig.cs:line 427
     --- End of inner exception stack trace ---
     at Mapster.TypeAdapterConfig.CreateMapExpression(CompileArgument arg) in C:\Projects\Mapster\src\Mapster\TypeAdapterConfig.cs:line 431
     at Mapster.TypeAdapterConfig.CreateMapExpression(TypeTuple tuple, MapType mapType) in C:\Projects\Mapster\src\Mapster\TypeAdapterConfig.cs:line 396
     at Mapster.Tool.Program.GenerateMappers(MapperOptions opt) in C:\Projects\Mapster\src\Mapster.Tool\Program.cs:line 63
     at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
     at Mapster.Tool.Program.Main(String[] args) in C:\Projects\Mapster\src\Mapster.Tool\Program.cs:line 19
```

Note, this .dll can be found in my /bin/Debug/net8.0 folder at the time that I run Mapster.Tool.

I checked the assembly version on the generated .dll as well using powershell.

Note: I censored  absolute paths on my local hard drive with '...'
```powershell
PS .../bin/Debug/net8.0> $strPath = '.../bin/Debug/net8.0/System.Text.Json.dll'
PS .../bin/Debug/net8.0> $Assembly = [Reflection.Assembly]::Loadfile($strPath)                                         
PS .../bin/Debug/net8.0> $AssemblyName = $Assembly.GetName()
PS .../bin/Debug/net8.0> 
PS .../bin/Debug/net8.0> $Assemblyversion = $AssemblyName.version
PS .../bin/Debug/net8.0> $AssemblyVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
9      0      0      0

PS .../bin/Debug/net8.0> $AssemblyName

Version        Name
-------        ----
9.0.0.0        System.Text.Json

PS .../bin/Debug/net8.0> $Assembly

GAC    Version        Location
---    -------        --------
False  v4.0.30319     .../bin/Debug/net8.0/System.Text.Json.dll
```

Any ideas? I'm flummoxed.
