### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by ljf88** [MapsterMapper/Mapster#722]
Use Version：7.4.0    

    Source Class：
    public class BaseResponse
    {
       public string? TraceId { get; set; }
        public Guid InvoiceId { get; set; }
        public GatewayActionResultEnum ActionResult { get; set; }
        public string? ActionResultDescription { get; set; }
        public string? UniqueId { get; set; }
        public BaseRequest RawRequest { get; set; }
        public object RawResponse { get; set; }
        public dynamic? ResponseEntity { get; set; }
        public HttpStatusCode? StatusCode { get; set; }
        public List<Error> Errors { get; set; } = [];
        public bool IsRetry { get; set; }
    }

    public record Error(string Description, string? Code, string? Name);

    public class PrepareResponse : BaseResponse
    {
    }

Target Class：
    public class BaseRes
    {
        public Guid InvoiceId { get; set; }
        public GatewayActionResultEnum ActionResult { get; set; }
        public string? ActionResultDescription { get; set; }
        public string? UniqueId { get; set; }
        public object RawRequest { get; set; }
        public string RawResponse { get; set; }
        public dynamic? ResponseEntity { get; set; }
        public bool IsFriendlyTip { get; set; } = false;
        public string? FriendlyTip { get; set; }
        public bool IsRetry { get; set; }
        public string? TraceId { get; set; }
    }

    public class PrepareRes : BaseRes
    {
        public Payment Payment { get; set; }
        public string? RedirectUrl { get; set; }
    }
  
  public partial class Payment
  {
      public Guid PaymentId { get; set; }
      public string GatewayPayerId { get; set; } = null!;
      public short? LastStatus { get; set; }
      public DateTime CreateTime { get; set; }
      public string GatewayPaymentId { get; set; } = null!;
      public string Currency { get; set; } = null!;
      public decimal Price { get; set; }
      public string? Memo { get; set; }
      public string GatewayPayerName { get; set; } = null!;
  }

test data：
{"InvoiceId":"03f38e68-792a-48c0-a8ee-1d7877b2f7c9","ActionResult":1,"ActionResultDescription":null,"UniqueId":null,"RawRequest":null,"RawResponse":null,"ResponseEntity":null,"StatusCode":null,"Errors":[],"IsRetry":false,"TraceId":null}

call code：
   source.Adapt<TDestination>(TypeAdapterConfig.GlobalSettings) ;
  or
  source.Adapt<TDestination>();

Error message："Object reference not set to an instance of an object."
StackTrack："   在 Mapster.TypeAdapter.Adapt[TDestination](Object source, TypeAdapterConfig config)"

description：
  When deleting the TraceId attribute in the baseResponse class or changing the TraceId attribute in the source and target classes from string? to string, the conversion works fine.

**Comment by ljf88** [comment]
Supplementary Description：
If you change the type of TraceId to e.g. int?, long?, the conversion is also normal

**Comment by stagep** [comment]
Please try with the latest prerelease version. If your issue is still occurring then please reopen this issue. Thanks.

**Comment by matteo-mosca** [comment]
Having the exact same issue. Added a new string? property to both our entity and our dto with the same name, where there were already a dozen properties including other nullable strings, and suddenly Mapster gives a nullreferenceexception when doing the adapt. If I change the property to non nullable string it works.

Sounds like a bug in the codegen part, the exception detail points to a non specified closure method.

**Comment by DocSvartz** [comment]
@matteo-mosca You can write stack trace?

**Comment by matteo-mosca** [comment]
> [@matteo-mosca](https://github.com/matteo-mosca) You can write stack trace?

Sure, although I don't know how much help it can be.

`System.NullReferenceException: Object reference not set to an instance of an object.
at lambda_method1288(Closure, Object at Mapster.TypeAdapter.Adapt[TDestination](Object source, TypeAdapterConfig config)
at Mapster.TypeAdapter.Adapt[TDestination](Object source)
at RedactedNamespace.CrudService.MapToDto(TEntity entity)`

**Comment by DocSvartz** [comment]
This error is related to calling a method on an instance of object when it is null.
So far I was able to get this, if I specify something like this in the configuration.

```
 TypeAdapterConfig<SimplePoco, Destination>
     .NewConfig()
     .Map(destination => destination.TraceId, source => source .TraceId.ToString());

//when  source.TraceId == null 
```

**Comment by matteo-mosca** [comment]
> This error is related to calling a method on an instance of object when it is null. So far I was able to get this, if I specify something like this in the configuration.
> 
> ```
>  TypeAdapterConfig<SimplePoco, Destination>
>      .NewConfig()
>      .Map(destination => destination.TraceId, source => source.TraceId.ToString());
> 
> //when  source.TraceId == null 
> ```
> 
> > If I change the property to non nullable string it works.
> 
> Here did you mean source (Entity) ? You repository in this case (when Property is not "string?") return null or String.Empty ?

Our entities are POCO objects with no logic, and we use EF core. Here's a sample:


    [Column(TypeName = "nvarchar(150)")]
    public string Name { get; set; } = null!;

    [Column(TypeName = "nvarchar(150)")]
    public string? SupplierGroup { get; set; }

    [Column(TypeName = "nvarchar(150)")]
    public string? AlternativeName { get; set; }

    [Column(TypeName = "varchar(150)")]
    public string Address1 { get; set; } = null!;

    [Column(TypeName = "varchar(150)")]
    public string? Address2 { get; set; }

    [Column(TypeName = "varchar(150)")]
    public string? Address3 { get; set; }

    [Column(TypeName = "varchar(150)")]
    public string City { get; set; } = null!;

    public int CountryId { get; set; }
    public CountryEntity? Country { get; set; } = null!;

    [Column(TypeName = "varchar(150)")]
    public string State { get; set; } = null!;

    [Column(TypeName = "varchar(150)")]
    public string PostalCode { get; set; } = null!;


As you can see we use nullable strings as well as non nullable strings. We have dozens of entities and everything worked fine. Suddenly one dev added another nullable string to an entity:

    [Column(TypeName = "nvarchar(150)")]
    public string? UserNumber { get; set; }

And the error started occurring. Weird things: renaming the property to anything else doesn't change anything, error keeps happening. To "solve" the error, I have to either remove the property or make it a non nullable string.

As for your last question, we properly use nullable everywhere so for non nullable strings the repository returns string empty, but the repository is not involved in the problem. I unit tested this thing excluding the repository altogether and the error happens.

I already spent 2 full working days on this and I cannot explain this anymore than what I wrote here.

**Comment by refreshingqin** [comment]
how to resolve this problem? It's been almost a year now

**Comment by DocSvartz** [comment]
Hello @refreshingqin  can you provide a non-working example and mapping configuration?
The case I found that I described above does not fit the initial statements.

**Comment by refreshingqin** [comment]
like this simple example 
`public class User
{
    public string? Id { get; set; }
    public string? Name { get; set; }

    public People People { get; set; }
}


public class People
{
    public string? Id { get; set; }
    public string? Name { get; set; }
}

public class UserDto
{
    public string? Id { get; set; }
    public string? Name { get; set; }

    public PeopleDto People { get; set; }
}

public class PeopleDto
{
    public string? Id { get; set; }
    public string? Name { get; set; }
}

then use user map to userDto 
var user = new User();
var userDto= user.Adapt<UserDto>();
`

**Comment by DocSvartz** [comment]
@refreshingqin In your case it is due to the use of Nullable Annotation for reference types.
 all member in #nullable with out ? in enable section mark as never not null .
For this reason, no additional Null check is created.

you can use 

`public PeopleDto? People { get; set; }`

or 
`#nullable disable `
in file where where do you define Class User if property People can receive a null value.

In one of the new PRs I changed this behavior. In one of the new PRs i changed this behavior to unconditionally create a null check for reference types

**Comment by refreshingqin** [comment]
after my testing ,If only one Nullable type and one Object type are used in the main class, there is no problem. However, if there are multiple Nullables and one Object, a bug may occur

this sample is ok 
`
  public class User
  {
      public string? Id { get; set; }
    

      public People People { get; set; }
  }

`
also pass test
`  
public class User
 {
     public string? Id { get; set; }
     public string? Name { get; set; }
 
 }
`
but next will be thow exception 
 public class User
 {
     public string? Id { get; set; }
     public string? Name { get; set; }

     public People People { get; set; }
 }

`

**Comment by refreshingqin** [comment]
@DocSvartz i don't think in case of People   .because of the second demo can pass the test

**Comment by DocSvartz** [comment]
@refreshingqin 
In #nullable enable context both cases should return fail. 
Because a non-nullable property should not return null.

**Comment by refreshingqin** [comment]
but  i use People? People also throw exception ，if User just exist only one Propery is string? type ，can't throw exception  . but more one and exist Object Type Property will throw exception .could you fixed it?

**Comment by DocSvartz** [comment]
Does this also give an exception?
Perhaps People itself also has properties that are reset when they shouldn't be?

 public class User
 {
     public string? Id { get; set; }
     public string? Name { get; set; }
     public People? People { get; set; } // This works for me without errors.
 }

**Comment by refreshingqin** [comment]
got it ! Thanks !

**Comment by liuliucn** [comment]
@DocSvartz  @refreshingqin 
I've also encountered the same problem recently. I'm sorry, but I don't know how to solve it? It means adding a ```new() ``` on property?
